# Generated by Django 3.1.4 on 2020-12-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
