# Generated by Django 3.1.4 on 2020-12-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_auto_20201231_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, default='/static/img/Screenshot_24.png', null=True, upload_to='images/'),
        ),
    ]
