# Generated by Django 3.1.4 on 2020-12-31 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0008_auto_20201231_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
