# Generated by Django 3.1.4 on 2020-12-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0010_auto_20201231_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='image',
            new_name='click',
        ),
    ]
