# Generated by Django 3.1.4 on 2020-12-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0011_auto_20201231_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='click',
            new_name='image',
        ),
    ]
