# Generated by Django 3.1.5 on 2021-01-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0012_auto_20201231_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
